/**
 * Pipeline Types
 *
 * Types for the puzzle pipeline engine that auto-generates and schedules puzzles.
 */

import type { Genre } from '../../types';

/**
 * Pipeline configuration options.
 * Stored in database per genre.
 */
export interface PipelineConfig {
  /** Whether auto-generation is enabled */
  enabled: boolean;
  /** Number of days to maintain scheduled puzzles (default: 30) */
  rollingWindowDays: number;
  /** Genre this config applies to */
  genre: Genre;
  /** Minimum approved groups per color before triggering AI generation (default: 10) */
  minGroupsPerColor: number;
  /** Number of groups to generate when pool is low (default: 20) */
  aiGenerationBatchSize: number;
}

/**
 * Default pipeline configuration values
 */
export const DEFAULT_PIPELINE_CONFIG: Omit<PipelineConfig, 'genre'> = {
  enabled: false,
  rollingWindowDays: 30,
  minGroupsPerColor: 10,
  aiGenerationBatchSize: 20,
};

/**
 * Result of a pipeline fill operation
 */
export interface PipelineFillResult {
  /** Number of puzzles successfully created */
  puzzlesCreated: number;
  /** Number of empty days that couldn't be filled */
  emptyDaysRemaining: number;
  /** Whether AI generation was triggered due to low pool */
  aiGenerationTriggered: boolean;
  /** Number of groups generated by AI */
  groupsGenerated: number;
  /** Number of groups successfully saved */
  groupsSaved: number;
  /** Groups generated/saved by color */
  groupsByColor: {
    yellow: { generated: number; saved: number };
    green: { generated: number; saved: number };
    blue: { generated: number; saved: number };
    purple: { generated: number; saved: number };
  };
  /** List of errors encountered during fill */
  errors: PipelineError[];
}

/**
 * Pipeline error with context
 */
export interface PipelineError {
  /** Date that failed (YYYY-MM-DD) */
  date: string;
  /** Error message */
  message: string;
  /** Error code for programmatic handling */
  code: PipelineErrorCode;
}

/**
 * Pipeline error codes
 */
export type PipelineErrorCode =
  | 'INSUFFICIENT_GROUPS'
  | 'DUPLICATE_PUZZLE'
  | 'GENERATION_FAILED'
  | 'STORAGE_ERROR';

/**
 * Group availability by color.
 * Used to check pool health before pipeline operations.
 */
export interface GroupAvailability {
  /** Count of approved yellow groups */
  yellow: number;
  /** Count of approved green groups */
  green: number;
  /** Count of approved blue groups */
  blue: number;
  /** Count of approved purple groups */
  purple: number;
  /** Total approved groups across all colors */
  total: number;
  /** Whether there are enough groups to create at least one puzzle */
  sufficient: boolean;
}

/**
 * Pipeline status for UI display
 */
export interface PipelineStatus {
  /** Whether pipeline is currently running */
  isRunning: boolean;
  /** Number of days currently scheduled */
  scheduledDays: number;
  /** Number of empty days in rolling window */
  emptyDays: number;
  /** Pool health by color */
  poolHealth: GroupAvailability;
  /** Last fill result (if any) */
  lastFillResult?: PipelineFillResult;
}

/**
 * Pipeline stages for progress tracking
 */
export type PipelineStage =
  | 'idle'
  | 'checking-pool'
  | 'generating-yellow'
  | 'generating-green'
  | 'generating-blue'
  | 'generating-purple'
  | 'verifying-items'
  | 'saving-groups'
  | 'creating-puzzles'
  | 'complete'
  | 'error';

/**
 * Pipeline stage labels for UI display
 */
export const PIPELINE_STAGE_LABELS: Record<PipelineStage, string> = {
  'idle': 'Ready',
  'checking-pool': 'Checking group pool...',
  'generating-yellow': 'Generating easy groups (yellow)...',
  'generating-green': 'Generating medium groups (green)...',
  'generating-blue': 'Generating hard groups (blue)...',
  'generating-purple': 'Generating expert groups (purple)...',
  'verifying-items': 'Verifying items...',
  'saving-groups': 'Saving groups...',
  'creating-puzzles': 'Creating puzzles...',
  'complete': 'Complete',
  'error': 'Error',
};

/**
 * Progress info for pipeline UI
 */
export interface PipelineProgress {
  stage: PipelineStage;
  /** Optional: current item being processed */
  currentItem?: string;
  /** Optional: progress count (e.g., "5/30") */
  progress?: { current: number; total: number };
}

/**
 * Callback for reporting pipeline stage changes
 */
export type PipelineStageCallback = (stage: PipelineStage) => void;
